name: CI
on:
  push:
    branches-ignore:
      - develop
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.14.1]
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1c5c1375b3817ad821719597effe8e3d6f764930
        with:
          node-version: ${{ matrix.node-version }}
      - name: Before Install
        run: |
          [[ -e ./scripts/pre-install.sh ]] && ./scripts/pre-install.sh
          npm install -g npm@6.13.6
          yarn global add typescript
          yarn global add webpack
          echo "node $(node --version)"
          echo "npm $(npm --version)"
          echo "yarn $(yarn --version)"
      - name: Install
        run: |
          yarn
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test