name: Push
on: [push]

jobs:
  build:
    # if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Use Node.js 12.14.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.14.1
      - name: Before Install
        run: |
          npm install -g npm@6.13.6
          yarn global add typescript
          yarn global add webpack
      - name: Install
        run: |
          yarn install
      - name: Lint
        run: |
          yarn run lint
      - name: Test
        run: |
          yarn run test